# Generated by Django 3.2.5 on 2021-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
