# Generated by Django 3.2.5 on 2021-07-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210717_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icons',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
